Reverted commit#7234, as these changes caused the dynamic linker on OSX to throw the following error during universe generation: "dyld: Symbol not found: __Z17GetUniverseObjecti" (referenced from freeorioncommon.dylib).
git-svn-id: svn://svn.code.sf.net/p/freeorion/code/trunk@7242 dbd5520b-6a0a-0410-a553-f54834df5b05